#main file that is ran to display the list of different groups in the data set and the graphs 

#importing the constructors and class made in Mod1_patient
from Mod1_patient import Patient

#import the proper packages for creating the plots and standard deviation 
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
import statistics
import pandas as pd
from sklearn.linear_model import LinearRegression

#These list will be used to create the scatter plots and bar graph 
age_of_onset_4_4 = []
age_of_onset_3_4 = []
age_of_onset_2_4 = []
age_of_onset_3_3 = []
age_of_onset_3_2 = []
years_of_education_4_4 = []
years_of_education_3_4 = []
years_of_education_2_4 = []
years_of_education_3_3 = []
years_of_education_3_2 = []

#this calls the method created in the patient.py file that opens the CSV file and goes through the data according to the following methods 
filename = "/Users/janewyatt/Desktop/BME 2315 /Module 1/BME2315_Module1_Project/Metadata and Protein Data for Module 1.csv"
Patient.instantiate_from_csv(filename)

#Calling the method get_patients_with_4_4_gene to sort the patients in the CSV file into only patients with 4_4 gene 
print("\nList of All Patients with 4_4 Gene sorted by age of onset:\n")
for patient in Patient.get_patients_with_4_4_gene("4_4"):
    if patient.age_of_onset is not None and patient.years_of_education is not None:
        #this condition checks to make sure the patient has both age of onset and years of education data 
        age_of_onset_4_4.append(patient.age_of_onset)
        years_of_education_4_4.append(patient.years_of_education)
        #these append functions add the values that meet the condition into the proper list
    print(patient)
    #Printing the patients with 4_4 gene to keep the data organize 

#This block of the code does the same thing as the one from lines 30-39 but for the 3_4 gene 
print ("\nList of All Patients with 3_4 Gene sorted by age of onset:\n")
for patient in Patient.get_patients_with_3_4_gene("3_4"):
    if patient.age_of_onset is not None and patient.years_of_education is not None:
        age_of_onset_3_4.append(patient.age_of_onset)
        years_of_education_3_4.append(patient.years_of_education)
    print(patient)

#This block of the code does the same thing as the one from lines 30-39 but for the 2_4 gene 
print ("\nList of All Patients with 2_4 Gene sorted by age of onset:\n")
for patient in Patient.get_patients_with_2_4_gene("2_4"):
    if patient.age_of_onset is not None and patient.years_of_education is not None:
        age_of_onset_2_4.append(patient.age_of_onset)
        years_of_education_2_4.append(patient.years_of_education)
    print(patient)

#This block of the code does the same thing as the one from lines 30-39 but for the 3_3 gene 
print ("\nList of All Patients with 3_3 Gene sorted by age of onset:\n")
for patient in Patient.get_patients_with_3_3_gene("3_3"):
    if patient.age_of_onset is not None and patient.years_of_education is not None:
        age_of_onset_3_3.append(patient.age_of_onset)
        years_of_education_3_3.append(patient.years_of_education)
    print(patient)

#This block of the code does the same thing as the one from lines 30-39 but for the 3_2 gene 
print ("\nList of All Patients with 3_2 Gene sorted by age of onset:\n")
for patient in Patient.get_patients_with_3_2_gene("3_2"):
    if patient.age_of_onset is not None and patient.years_of_education is not None:
        age_of_onset_3_2.append(patient.age_of_onset)
        years_of_education_3_2.append(patient.years_of_education)
    print(patient)

if len(years_of_education_3_2) < 2:
    print("Unfortunately there is not enough data for a 3_2 regression.")
    #While writing the code we realized that there aren't any patients in the data set with a 3_2 gene and a recorded length of years spent in school or onset age 

#------------------------------------------------------------------------------------
#Creating the scatter plots using the the list in lines 15-24

#This is the scatter plot of 4_4 gene 
#At AI's reccommendation we converted the data list into numpy arrays because the array assist in reformating the data to make it easier to plot with the scikit-learn (the model that is performing the linear regression)
X = np.array(years_of_education_4_4).reshape(-1, 1)
y = np.array(age_of_onset_4_4)

#this tells python wich data sets to use for the x and y values for the line in the graph 
model = LinearRegression()
model.fit(X, y)

#these statistics model caculate the slope, intercept, and R-squared value
slope = model.coef_[0]
intercept = model.intercept_
r2 = model.score(X, y)

equation = f"y = {slope:.2f}x + {intercept:.2f}\nR² = {r2:.2f}"

#the following block of code displays the graph and the regression equation
plt.scatter(X[:, 0], y, color="blue")
plt.plot(X[:, 0], model.predict(X), color="red")
plt.text(
    #this formatting was generated by AI to keep the equation from being cut off when the graph was generated
    0.05,
    0.95,
    equation,
    transform=plt.gca().transAxes,
    color="red",
    verticalalignment="top",
    bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none"},
)
plt.xlabel("Years of Education")
plt.ylabel("Age of Onset")
plt.title("4_4: Years of Education vs Age of Onset")
plt.show()

#-------------------
# Scatter plot for data points with gene 3_4 
#the following code is the same as for lines 80-112 but for the 3_4 gene

X = np.array(years_of_education_3_4).reshape(-1, 1)
y = np.array(age_of_onset_3_4)

model = LinearRegression()
model.fit(X, y)

slope = model.coef_[0]
intercept = model.intercept_
r2 = model.score(X, y)

equation = f"y = {slope:.2f}x + {intercept:.2f}\nR² = {r2:.2f}"

plt.scatter(X[:, 0], y, color="blue")
plt.plot(X[:, 0], model.predict(X), color="red")
plt.text(
    0.05,
    0.95,
    equation,
    transform=plt.gca().transAxes,
    color="red",
    verticalalignment="top",
    bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none"},
)
plt.xlabel("Years of Education")
plt.ylabel("Age of Onset")
plt.title("3_4: Years of Education vs Age of Onset")
plt.show()
#-------------------
# Scatter plot for data points with gene 2_4 
#the following code is the same as for lines 80-112 but for the 2_4 gene

X = np.array(years_of_education_2_4).reshape(-1, 1)
y = np.array(age_of_onset_2_4)

model = LinearRegression()
model.fit(X, y)

slope = model.coef_[0]
intercept = model.intercept_
r2 = model.score(X, y)

equation = f"y = {slope:.2f}x + {intercept:.2f}\nR² = {r2:.2f}"

plt.scatter(X[:, 0], y, color="blue")
plt.plot(X[:, 0], model.predict(X), color="red")
plt.text(
    0.05,
    0.95,
    equation,
    transform=plt.gca().transAxes,
    color="red",
    verticalalignment="top",
    bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none"},
)
plt.xlabel("Years of Education")
plt.ylabel("Age of Onset")
plt.title("2_4: Years of Education vs Age of Onset")
plt.show()
#-------------------
# Scatter plot for data points with gene 3_3 
#the following code is the same as for lines 80-112 but for the 3_3 gene

X = np.array(years_of_education_3_3).reshape(-1, 1)
y = np.array(age_of_onset_3_3)

model = LinearRegression()
model.fit(X, y)

slope = model.coef_[0]
intercept = model.intercept_
r2 = model.score(X, y)

equation = f"y = {slope:.2f}x + {intercept:.2f}\nR² = {r2:.2f}"

plt.scatter(X[:, 0], y, color="blue")
plt.plot(X[:, 0], model.predict(X), color="red")
plt.text(
    0.05,
    0.95,
    equation,
    transform=plt.gca().transAxes,
    color="red",
    verticalalignment="top",
    bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none"},
)
plt.xlabel("Years of Education")
plt.ylabel("Age of Onset")
plt.title("3_3: Years of Education vs Age of Onset")
plt.show()
#-------------------
# Scatter plot for data points with gene 3_2
# the following code is the same as for lines 80-112 but for the 3_2 gene

X = np.array(years_of_education_3_2).reshape(-1, 1)
y = np.array(age_of_onset_3_2)

if len(X) >= 2: #this conditional checks if there are at least 2 data points in the group because if its not 2 points or more the linear regression method will not work 
    model = LinearRegression()
    model.fit(X, y)

    slope = model.coef_[0]
    intercept = model.intercept_
    r2 = model.score(X, y)

    equation = f"y = {slope:.2f}x + {intercept:.2f}\nR² = {r2:.2f}"

    plt.scatter(X[:, 0], y, color="blue")
    plt.plot(X[:, 0], model.predict(X), color="red")
    plt.text(
        0.05,
        0.95,
        equation,
        transform=plt.gca().transAxes,
        color="red",
        verticalalignment="top",
        bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none"},
    )
    plt.xlabel("Years of Education")
    plt.ylabel("Age of Onset")
    plt.title("3_2: Years of Education vs Age of Onset")
    plt.show()

#-------------------------------------------------------------------

#Code that groups the patients by length of time they were educated 

#First create the empty lists to store the data needed for the bar graph 

patients_0_13_years_educated_age_onset = []
patients_13_16_years_educated_age_onset = []
patients_16_20_years_educated_age_onset = []
patients_20_plus_years_educated_age_onset = []

#call the method made in the patient class that gets the number of patients with 0-13 years of education 
print("\nPatients with 0-13 years of education:\n")
for patient in Patient.get_patients_number_of_years_educated(0, 13):
    if patient.age_of_onset is not None:
        #this condition makes sure that only patients with a recorded age of onset is added to the sub data set for 0-13 years of education 
        patients_0_13_years_educated_age_onset.append(patient.age_of_onset)
    print(patient)

#this block of code is the same as 252-257 but for 13-16 years of education
print("\nPatients with 13-16 years of education:\n")
for patient in Patient.get_patients_number_of_years_educated(13, 16):
    if patient.age_of_onset is not None:
        patients_13_16_years_educated_age_onset.append(patient.age_of_onset)
    print(patient)

#this block of code is the same as 252-257 but for 16-20 years of education
print("\nPatients with 16-20 years of education:\n")
for patient in Patient.get_patients_number_of_years_educated(16, 20):
    if patient.age_of_onset is not None:
        patients_16_20_years_educated_age_onset.append(patient.age_of_onset)
    print(patient)

#this block of code is the same as 252-257 but for 20+ years of education
print("\nPatients with 20+ years of education:\n")
for patient in Patient.get_patients_number_of_years_educated(20, 100):
    if patient.age_of_onset is not None:
        patients_20_plus_years_educated_age_onset.append(patient.age_of_onset)
    print(patient)

#Following the built in AIs Advice reformatting the list into arrays for the proper format for the statistics models 
x_patients_0_13_years_educated_age_onset = np.array(patients_0_13_years_educated_age_onset)
x_patients_13_16_years_educated_age_onset = np.array(patients_13_16_years_educated_age_onset)
x_patients_16_20_years_educated_age_onset = np.array(patients_16_20_years_educated_age_onset)
x_patients_20_plus_years_educated_age_onset = np.array(patients_20_plus_years_educated_age_onset)

#caculating the mean of each group using the np model for mean 
patients_0_13_years_educated_age_onset_mean = np.mean(x_patients_0_13_years_educated_age_onset)
patients_13_16_years_educated_age_onset_mean = np.mean(x_patients_13_16_years_educated_age_onset)
patients_16_20_years_educated_age_onset_mean = np.mean(x_patients_16_20_years_educated_age_onset)
patients_20_plus_years_educated_age_onset_mean = np.mean(x_patients_20_plus_years_educated_age_onset)

#caculating the std of each group using the std model 
patients_0_13_years_educated_age_onset_std = np.std(x_patients_0_13_years_educated_age_onset)
patients_13_16_years_educated_age_onset_std = np.std(x_patients_13_16_years_educated_age_onset)
patients_16_20_years_educated_age_onset_std = np.std(x_patients_16_20_years_educated_age_onset)
patients_20_plus_years_educated_age_onset_std = np.std(x_patients_20_plus_years_educated_age_onset)

#printing the results of the mean and standard deviation for each data group 
print(f'\nAge of onset for 0-13 years of education: {patients_0_13_years_educated_age_onset_mean} ± {patients_0_13_years_educated_age_onset_std}')
print(f'\nAge of onset for 13-16 years of education: {patients_13_16_years_educated_age_onset_mean} ± {patients_13_16_years_educated_age_onset_std}')
print(f'\nAge of onset for 16-20 years of education: {patients_16_20_years_educated_age_onset_mean} ± {patients_16_20_years_educated_age_onset_std}')
print(f'\nAge of onset for 20+ years of education: {patients_20_plus_years_educated_age_onset_mean} ± {patients_20_plus_years_educated_age_onset_std}')

#Creating the column names for the bar chart
year_educating = ['0-13', '13-16', '16-20', '20+']
#creating the arrays for the bar chart
mean_age_onset = [
    patients_0_13_years_educated_age_onset_mean,
    patients_13_16_years_educated_age_onset_mean,
    patients_16_20_years_educated_age_onset_mean,
    patients_20_plus_years_educated_age_onset_mean,
]
#creating the arrays of standard deviations for the bar chart
stdev_age_onset = [patients_0_13_years_educated_age_onset_std, patients_13_16_years_educated_age_onset_std, patients_16_20_years_educated_age_onset_std, patients_20_plus_years_educated_age_onset_std]

#This line is copied from the class example. It creates an asymmetric error bar which is the standard devaition bar that extends above each group in the bar graph 
yerr = [np.zeros(len(mean_age_onset)), stdev_age_onset]

#This block of code formats the bar graph 
plt.bar(year_educating, mean_age_onset, yerr=yerr, capsize=10, color=["blue", "orange"])
plt.title("Average Age of Onset Mediated by Years of Education")
plt.xlabel("Years of Education")
plt.ylabel("Average Age of Onset (age)")

#This block of code performs the one-way ANOVA test to determine if there are significant differences between the groups that would indicate level of education plays a role in deffering symptoms 
f_stat, p_value = stats.f_oneway(x_patients_0_13_years_educated_age_onset, x_patients_13_16_years_educated_age_onset, x_patients_16_20_years_educated_age_onset, x_patients_20_plus_years_educated_age_onset)
print("\nF-statistic:", f_stat)
print("\np-value:", p_value)
plt.text(
    0.98,
    0.98,
    f"One-Way ANOVA: p = {p_value:.3f}",
    transform=plt.gca().transAxes,
    ha="right",
    va="top",
    fontsize=12,